#!/bin/bash

RESOURCE_TYPE=${1:-pods}
NAMESPACE=${2:-default}


echo "Resource,Namespace,Name,CPU,Memory"
kubectl top $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line; do
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')
  echo "$RESOURCE_TYPE,$NAMESPACE,$NAME,$CPU,$MEMORY"
done
