apiVersion: v1                                                                
kind: Pod                                                                     
metadata:                                                                     
  name: app                                                                   
  labels:                                                                     
    app: demo                                                                 
    run: demo                                                                 
spec:                                                                         
  containers:                                                                 
  - name: app-container                                                       
    image: <YOUR_IMAGE_HERE>                                                  
    ports:                                                                    
    - containerPort: 8000                                                     
      name: http                                                              
    livenessProbe:                                                            
      httpGet:                                                                
        path: /                                                               
        port: 8000                                                            
      initialDelaySeconds: 5                                                  
      periodSeconds: 5                                                        
    readinessProbe:                                                           
      httpGet:                                                                
        path: /ready                                                          
        port: 8000                                                            
      initialDelaySeconds: 5                                                  
      periodSeconds: 5  